import 'package:flutter/material.dart';

const Color primaryColor = Colors.indigo;
final Color primary200Color = Colors.indigo[200];
const Color deepPurpleColor = Colors.deepPurpleAccent;
const Color blackColor = Colors.black;
const Color whiteColor = Colors.white;
const Color redColor = Colors.red;
const Color orangeColor = Colors.orange;
const Color redAccentColor = Colors.redAccent;
final Color red900Color = Colors.red[900];
final Color grey400Color = Colors.grey[400];
final Color grey500Color = Colors.grey[500];
final Color pink600Color = Colors.pink[600];
final Color grey900Color = Colors.grey[900];
final Color grey50Color = Colors.grey[50];
final Color grey700Color = Colors.grey[700];
final Color grey800Color = Colors.grey[800];
final Color grey600Color = Colors.grey[600];
final Color deepPurple100Color = Colors.deepPurpleAccent[100];
const Color transparent = Colors.transparent;